---
title: "Prep ST data for deconv (Covid Lungs)"
author: "Yuvarani Masarapu"
output: 
  html_document:
    self_contained: true
    highlight: tango
    df_print: paged
    code_folding: hide
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: false
      smooth_scroll: true    
---

# Load each of the R objects for st data.

```{r setup, include=FALSE}
knitr::opts_knit$set(progress=TRUE,verbose=TRUE)
knitr::opts_chunk$set(message=FALSE, warning=FALSE, result='hold',fig.width=10, fig.height = 8)
```


```{r packages}
suppressPackageStartupMessages(require(Matrix))
suppressPackageStartupMessages(require(dplyr))
suppressPackageStartupMessages(require(Seurat))
suppressPackageStartupMessages(require(SeuratDisk))
```

```{r load}
data.int <- readRDS(file = paste(indir, "/", "lung.integrated.updated_08_12_2021.rds", sep = ""))
```

```{r}
table(data.int$section_id)
```

```{r}
# keep only RNA assay 
data.int@active.assay = "Spatial"

data.int = DietSeurat(data.int, assays = "Spatial")
data.int@tools$Staffli = NULL

# @assays$RNA@data contains counts.
# Garbage collection command
g = gc(verbose = F)
```

# SCP1219, need data in .tsv as sc data is not provided in .h5ad format by authors

```{r}
df <- data.int@assays$Spatial@counts

write.table(df, file= paste(indir,'/stereoscope-covidlung-input/SCP1219/st-data_in_tsv/st-covid-data_for_SCP1219.tsv'  ,sep = ""), quote=FALSE, sep='\t', col.names = TRUE, row.names = TRUE)

lung.genes  = rownames(data.int)
```

# SCP1052, need data in .h5ad, split by each section

```{r}
indir = getwd()
outdir = paste(indir, "/stereoscope-covidlung-input/SCP1052/st-data_per_sample-CovidLung/", sep = "")
dir.create(outdir, showWarnings = F)

alldata = SplitObject(data.int, split.by = "section_id")

for (sample in names(alldata)){
  print(sample)
  sfile = file.path(outdir, paste0(sample,".h5Seurat"))
  hfile = file.path(outdir, paste0(sample,".h5ad"))
  if (!file.exists(hfile)){
    SaveH5Seurat(alldata[[sample]], filename = sfile, overwrite = T)
    Convert(sfile, dest = "h5ad", overwrite = T)
    file.remove(sfile)
  }
}

lung.genes  = rownames(data.int)

rm(data.int, alldata)
# Garbage collection command
g = gc(verbose = F)
```

### Session info

```{r}
sessionInfo()
```
